stages: 
  - deploy

deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - pushes
    - dev
  environment: production
  variables:
    RAILWAY_TOKEN: "d09830df-94e9-4de9-ab12-0f9dc8f908c2"
    RAILWAY_SERVICE_NAME: "api-core"
  script:
    - echo "Deploying application..."
    # - echo "Variables are '$RAILWAY_TOKEN' and '$RAILWAY_SERVICE_NAME'"
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d
    - echo "Application successfully deployed."
